# Generated by Django 4.1 on 2022-08-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='C:/Users/johnp/Desktop/codestuff/voxenfree/voxenfree/media'),
            preserve_default=False,
        ),
    ]
