# Generated by Django 4.1 on 2022-08-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxcore', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='set',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
