# Generated by Django 4.1 on 2022-08-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voxcore', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
