# Generated by Django 4.1 on 2022-08-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxcore', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
