# Generated by Django 4.1 on 2022-08-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxcore', '0006_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
